from django.contrib import admin

# Register your models here.
from . import models
admin.site.register(models.Produit)
admin.site.register(models.Category)
admin.site.register(models.Coupon)
# register all models in the admin site
admin.site.register(models.Pairingcode)
admin.site.register(models.Shippingfees)
admin.site.register(models.Mark)
admin.site.register(models.Client)
admin.site.register(models.Order)
admin.site.register(models.Orderitem)
admin.site.register(models.Bonlivraison)
admin.site.register(models.Facture)
admin.site.register(models.Livraisonitem)
admin.site.register(models.Supplier)
admin.site.register(models.Outfacture)
admin.site.register(models.Carlogos)
admin.site.register(models.Itemsbysupplier)
admin.site.register(models.PaymentSupplier)
admin.site.register(models.PaymentClientbl)
admin.site.register(models.PaymentClientfc)
admin.site.register(models.Ordersnotif)
admin.site.register(models.Connectedusers)
admin.site.register(models.Avoirclient)
admin.site.register(models.Stockin)
admin.site.register(models.Promotion)
admin.site.register(models.UserSession)
admin.site.register(models.Refstats)
admin.site.register(models.Cart)
admin.site.register(models.Cartitems)
admin.site.register(models.Represent)
admin.site.register(models.Wich)
admin.site.register(models.Wishlist)
# admin.site.register(models.Cartitems)
# admin.site.register(models.Cartitems)
# admin.site.register(models.Cartitems)
# admin.site.register(models.Cartitems)
# admin.site.register(models.Cartitems)
# admin.site.register(models.Cartitems)
# admin.site.register(models.Cartitems)
# admin.site.register(models.Cartitems)

