
from django.urls import path
from . import views
from django.views.defaults import page_not_found
urlpatterns = [
    path('', views.home, name='home'),
    path('product/<int:id>', views.product, name='product'),
    path('clientdashboar', views.clientdashboar, name='clientdashboar'),
    path('searchref', views.searchref, name='searchref'),
    path('commande', views.commande, name='commande'),
    path('orders', views.orders, name='orders'),
    path('orderitems/<int:id>', views.orderitems),
    path('dilevered/<int:id>', views.dilevered),
    path('paied/<int:id>', views.paied),
    path('marks/products/<int:id>', views.products),
    path('categories/products/<int:id>', views.productscategories),
    path('marques/products/<int:id>', views.productsmarks),
    path('login', views.loginpage, name='loginpage'),
    path('ibra', views.ibra, name='ibra'),
    path('catalog', views.catalog, name='catalog'),
    path('salsemanorders/<str:str_id>', views.salsemanorders, name='salsemanorders'),
    path('logoutuser', views.logoutuser, name='logoutuser'),
    path('clients', views.clients, name='clients'),
    path('addclient', views.addclient, name='addclient'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('partners', views.partners, name='marques'),
    path('profile', views.profile, name='profile'),
    path('editinfoclient', views.editinfoclient, name='editinfoclient'),
    path('updatepassword', views.updatepassword, name='updatepassword'),
    path('developer', views.developer, name='developer'),
    path('cart', views.cart, name='cart'),
    path('ordersforeach', views.ordersforeach, name='ordersforeach'),
    path('sitemap', views.sitemap, name='sitemap'),
    path('makeuserconnected', views.makeuserconnected, name='makeuserconnected'),
    path('loginuser', views.loginuser, name='login'),
    path('catalogpage', views.catalogpage, name='catalogpage'),
    path('client/clientshome', views.clientshome, name='clientshome'),
    path('client/searchglobal', views.searchglobal, name='searchglobal'),
    path('productdata', views.productdata, name='productdata'),
    path('searchrefphone', views.searchrefphone, name='searchrefphone'),
    path('addtocart', views.addtocart, name='addtocart'),
    path('removeitemfromcart', views.removeitemfromcart, name='removeitemfromcart'),
    path('removecart', views.removecart, name='removecart'),
    path('getitemsincart', views.getitemsincart, name='getitemsincart'),
    path('addtowhishlist', views.addtowhishlist, name='addtowhishlist'),
    path('updatecartitem', views.updatecartitem, name='updatecartitem'),
    path('updatewishitem', views.updatewishitem, name='updatewishitem'),
    path('getitemsincart', views.getitemsincart, name='getitemsincart'),
    path('getitemsinwishlist', views.getitemsinwishlist, name='getitemsinwishlist'),
    path('removeitemfromwish', views.removeitemfromwish, name='removeitemfromwish'),
    path('switchtocart', views.switchtocart, name='switchtocart'),
    path('replicata', views.replicata, name='replicata'),
    path('notifications', views.notifications, name='notifications'),
    path('catalogpermission', views.catalogpermission, name='catalogpermission'),
    path('newarrivage', views.newarrivage, name='newarrivage'),
    path('allproducts', views.allproducts, name='allproducts'),
    path('B152242/AZEDurtghh/LK1225Kll/84522KLMM', views.ordersnotsent, name='ordersnotsent'),
    path('sendordertoserver', views.sendordertoserver, name='sendordertoserver'),
    path('workingclient', views.workingclient, name='workingclient'),
    path('relveclientforrep', views.relveclientforrep, name='relveclientforrep'),
    path('getproducdataforsuppliers', views.getproducdataforsuppliers, name='getproducdataforsuppliers'),
    # path('clientshome', views.clientshome, name='clientshome'),
    # path('clientshome', views.clientshome, name='clientshome'),
    # path('clientshome', views.clientshome, name='clientshome'),
    # path('clientshome', views.clientshome, name='clientshome'),
    # path('clientshome', views.clientshome, name='clientshome'),
    # path('clientshome', views.clientshome, name='clientshome'),
    # path('clientshome', views.clientshome, name='clientshome'),
]
